-- ALTER TABLE jobs
-- ADD COLUMN tech_skills smallint[],
-- ADD COLUMN work_modes smallint[],
-- ADD COLUMN types_of_work smallint[],
-- ADD COLUMN exp_levels smallint[],
-- ADD COLUMN employment_types smallint[];